### ISSUE TITLE
non-traslated areas

### ISSUE THREAD

**Issue by sanwhere** [tolgaaaltas/flarum-ext-turkish#2]
Flagrow Ads Extension Admin Panel: 
- flagrow-ads.admin.settings.start-from-post
- flagrow-ads.admin.settings.between-n-posts
- flagrow-ads.admin.positions.under-header.title
- flagrow-ads.admin.positions.between-posts.title
- flagrow-ads.admin.positions.under-nav-items.title
- flagrow-ads.admin.button.save
- flagrow-ads.admin.tab.description

Flagrow File Upload Extension Admin Panel:
- flagrow-upload.admin.labels.ovh-svfs.title
- flagrow-upload.admin.labels.ovh-svfs.container
- flagrow-upload.admin.labels.ovh-svfs.tenantid
- flagrow-upload.admin.labels.ovh-svfs.username
- flagrow-upload.admin.labels.ovh-svfs.password
- flagrow-upload.admin.labels.ovh-svfs.region
- flagrow-upload.admin.labels.watermark.title
- flagrow-upload.admin.help_texts.watermark
- flagrow-upload.admin.labels.watermark.toggle
- flagrow-upload.admin.labels.watermark.position
- flagrow-upload.admin.labels.watermark.file
- flagrow-upload.admin.labels.disable-hotlink-protection.title
- flagrow-upload.admin.help_texts.disable-hotlink-protection
- flagrow-upload.admin.labels.disable-hotlink-protection.toggle
- flagrow-upload.admin.labels.disable-download-logging.title
- flagrow-upload.admin.help_texts.disable-download-logging
- flagrow-upload.admin.labels.disable-download-logging.toggle
- flagrow-upload.admin.labels.preferences.mime_types
- flagrow-upload.admin.help_texts.mime_types
- flagrow-upload.admin.help_texts.download_templates

**Comment by tolgaaaltas** [comment]
Flagrow Ads and Flagrow Upload extensions not supported now. But in future, we will support these extensions. Probably i will translate for you in tomorrow. Regards.

**Comment by tolgaaaltas** [comment]
In 0.1.6, we added Upload, Ads and Baazar support. (fully new translate)
