### ISSUE TITLE
[İstek] ReFlar/webhooks

### ISSUE THREAD

**Issue by northeaster** [tolgaaaltas/flarum-ext-turkish#4]
https://github.com/ReFlar/webhooks eklentisi desteği getirir misiniz?

**Comment by tolgaaaltas** [comment]
Eklemeye çalışacağım kısa sürede. Bu aralar biraz yoğun bir süreçteyim. Anlayışınız için teşekkürler.

**Comment by northeaster** [comment]
https://upimager.com/image/image.cMLs
FreeFlarum'dan Türkçe dil uyumlu olmadığı için kaldırılmış.

**Comment by tolgaaaltas** [comment]
Evet, Doorman zaten taşınacak ama elle TR paketi düzeltebilirsiniz. Ben PR yapmıştım düzeltmek için ama yayınlanmadı diye biliyorum.

**Comment by tolgaaaltas** [comment]
Bunu kapatıyorum çünkü çok uzun süredir açık kaldı ve talebi karşılayamadım. Ancak önümüzdeki haftaya eklemeyi planlıyorum. Umarım önümüzdeki hafta listeye ekleyebilmiş olurum.
