### ISSUE TITLE
Facebook Çeviri Hatası

### ISSUE THREAD

**Issue by halilhanbadem** [tolgaaaltas/flarum-ext-turkish#5]
![image](https://user-images.githubusercontent.com/17130294/70361851-17199380-1894-11ea-9dbb-ce873934010d.png)

Beta 10 kullanıcısıyım ve çeviri eklentisi ile çevirmeme rağmen bir düzelme olmadı.
Önbellek temizliği gerçekleştirdim. Sonuç halen aynı.

Kontrol edebilirsiniz: https://yazilimtoplulugu.com

**Comment by tolgaaaltas** [comment]
Bu Core Pack içerisinde yer alan bir çeviri. Core paketi için 0.11.1 sürümünü yayınladım, paketi güncellediğinizde sorunun giderilmiş olması lazım. Güncelledikten sonra önbelleği temizlemeyi unutmayın.
