### ISSUE TITLE
Beta 13 sonrası sorunlar

### ISSUE THREAD

**Issue by northeaster** [tolgaaaltas/flarum-ext-turkish#7]
Beta 13'e flarum yükselttikten sonra bazı düzgün yerler bende bozuldu. Sıfırdan beta 13 kurup eklentinin kuran başkasında burası düzgün gözüküyor. Nedeni ne olabilir?

https://forum.sourceturk.net/assets/files/2020-05-07/1588860386-311142-image.png

**Comment by tolgaaaltas** [comment]
Muhtemelen uzantıya güncelleme gelmiştir ve ben fark etmemişimdir. Şimdi bir güncelleme yayınlayacaktım, yayınlamadan önce görmem iyi oldu. Teşekkürler, göz atacağım.

**Comment by tolgaaaltas** [comment]
Sanırım bu güncelleme ile düzelmiş olması lazım. Eğer düzelmediyse yeni bir Issue açabilirsin.

**Comment by tolgaaaltas** [comment]
Dosya adlarını flarum_profile_views.yml ve flarum_discussion_views.yml olarak değiştirmem gerek gibi gözüküyor ama en baştan beri uyguladığım formata da aykırı düşecek gibi gözüküyor. Geliştiriciye elektronik posta atıp düzeltebilir mi diye soracağım bir ara.

**Comment by northeaster** [comment]
Hala aynı sorun devam ediyor diye tamda ben yeni açacaktım. Başka bir forumda düzgün gözükmesini anlayamadım.
http://prntscr.com/sdvqwf - https://www.rustforum.com.tr/u/Kory
http://prntscr.com/sdvrcl - https://forum.sourceturk.net/u/northeaster

**Comment by tolgaaaltas** [comment]
> Hala aynı sorun devam ediyor diye tamda ben yeni açacaktım. Başka bir forumda düzgün gözükmesini anlayamadım.
> http://prntscr.com/sdvqwf - https://www.rustforum.com.tr/u/Kory
> http://prntscr.com/sdvrcl - https://forum.sourceturk.net/u/northeaster

Linguist ile ilgili satırları görüntülediğinde Türkçe değerleri boş mu gözüküyor yoksa dolu mu gözüküyor acaba? Şu anda Flarum tabanlı bir sitem olmadığı için ilgili kontrolleri tam olarak gerçekleştiremiyorum maalesef.

**Comment by northeaster** [comment]
forum/vendor/tolgaaaltas/flarum-ext-turkish/locale burada oluyor ise çeviri dosyaları eğer;
flarum_profile_views.yml ve flarum_discussion_views.yml dosyasını bu dizinde göremiyorum.

**Comment by tolgaaaltas** [comment]
Dosyalar michaelbelgium-flarum-discussion-views.yml ve michaelbelgium-flarum-profile-views.yml olarak adlandırılmış durumda. Çeviri paketindeki tüm uzantıların adları geliştirici-uzantı.yml formatında olduğu için ellemek istemiyorum açıkçası. Geliştiriciye söyleyeceğim, eğer olumlu bakmazsa dosya adlarını değiştirmekten başka çare yok.

**Comment by northeaster** [comment]
> > Hala aynı sorun devam ediyor diye tamda ben yeni açacaktım. Başka bir forumda düzgün gözükmesini anlayamadım.
> > http://prntscr.com/sdvqwf - https://www.rustforum.com.tr/u/Kory
> > http://prntscr.com/sdvrcl - https://forum.sourceturk.net/u/northeaster
> 
> Linguist ile ilgili satırları görüntülediğinde Türkçe değerleri boş mu gözüküyor yoksa dolu mu gözüküyor acaba? Şu anda Flarum tabanlı bir sitem olmadığı için ilgili kontrolleri tam olarak gerçekleştiremiyorum maalesef.

Linguist ile ilgili satırlar derken tam nereyi bahsediyorsunuz?
Test için kendi forumumun bilgilerini verebilirim yada test için forum kurabilirim.

**Comment by northeaster** [comment]
michaelbelgium/flarum-discussion-views
michaelbelgium/flarum-profile-views
Bu 2 eklenti hala bende tamamen ingilizce. Nedense Türkçe uzantıları yüklü iken. Bir çözüm bulamaz mıyız?

**Comment by tolgaaaltas** [comment]
Bu defa çözülmüş olması gerekiyor. Kendisi nihayet olması gereken standart forma getirmiş.

**Comment by northeaster** [comment]
Aynı sorun bende devam etmekte. Kişiye sordum burada cevap verdi. https://discuss.flarum.org/d/7339-discussion-views/188

**Comment by tolgaaaltas** [comment]
Hangi sürümü kullanıyorsunuz siz? Paket gerekli şekle göre güncellendi.

**Comment by northeaster** [comment]
| michaelbelgium-discussion-views  | v4.0.0
| michaelbelgium-profile-views     | v3.0.0

**Comment by tolgaaaltas** [comment]
Turkish Extensions Experience Pack'ten bahsediyordum.

**Comment by northeaster** [comment]
| tolgaaaltas-turkish              | 0.13.7  
| tolgaaaltas-lang-turkish         | 0.13.0

**Comment by tolgaaaltas** [comment]
Dediğim gibi, çalışmaması için bir sebep göremiyorum ben.

**Comment by northeaster** [comment]
https://forum.sourceturk.net/u/northeaster
Bakabilirsiniz. Last visitors ve  viewed 62 times kelimeleri mesela. Mail yada skype verirseniz ssh vereyim. Bir de siz inceleyin uygun bulursanız.
