### ISSUE TITLE
Çeviri Öneriler

### ISSUE THREAD

**Issue by northeaster** [tolgaaaltas/flarum-ext-turkish#8]
![image](https://user-images.githubusercontent.com/55854510/82757568-ee596c00-9de9-11ea-9fec-8bcbfae98df7.png)
Sabitle kelimesi yerine Sabitlenmiş kelimesi yazması daha uygun olacaktır.

**Comment by tolgaaaltas** [comment]
O alan sanırım tek bir değişkene sahip. Bir tartışmayı sabitlemek için kullandığınız sağ araçtaki ile aynı değeri kullanıyor sanırım. Flarum kurulu bir sitem olmadığı için şu anda hangi değişken olduğunu da görüntüleyemiyorum maalesef. Bu sorunu burada kapatıyorum çünkü bu flarum-lang-turkish için geçerli bir çeviri önerisi. Dilerseniz kopyala yapıştır yaparak oraya açabilirsiniz ama inceleyemiyorum maalesef. Tüm dil paketlerini kapatıp ilgili alandaki değişkeni görüntüleyip bana atarsanız mutlaka göz atarım.
