### ISSUE TITLE
İngilizce satırlar

### ISSUE THREAD

**Issue by northeaster** [tolgaaaltas/flarum-ext-turkish#9]
### Moderator warning ext:
It looks like there are no warnings here.

### Kullanıcı profil açıklaması kısmında açıklama girilmemiş ise, Fof user bio eklentisi olabilir:
Write something about yourself

**Comment by northeaster** [comment]
clarkwinkelmann/flarum-ext-popular-discussion-badge :
popular
Comments (including first post) >=
AND | Views (from third-party extension) >=
Add another condition

show password ext:
Show Password

Gördükçe buraya eklemeler yapacağım. Lütfen kapatmayalım.

**Comment by northeaster** [comment]
### bildirimlerde gördüğüm ingilizce satır:
(Burası kullanıcı adı) changed the tag

**Comment by northeaster** [comment]
https://discuss.flarum.org/d/24432-audit-log-free
https://github.com/clarkwinkelmann/flarum-ext-likes-received

Bu 2 eklentiyi de ekler misiniz?

**Comment by northeaster** [comment]
### Calendar(Events) uzantısı desteği ekler misiniz?

https://github.com/eddiewebb/flarum-calendar
https://extiverse.com/extension/webbinaro/flarum-calendar

**Comment by northeaster** [comment]
### Minecraft Avatars uzantısı desteği ekler misiniz?
https://github.com/Nearata/flarum-ext-minecraft-avatars
https://extiverse.com/extension/nearata/flarum-ext-minecraft-avatars

**Comment by northeaster** [comment]
### flarum-ext-login2seeplus uzantısı desteği ekler misiniz?
https://discuss.flarum.org/d/5168-login2see bu eklenti paketiniz de var ama bu eklenti artık çalışmıyor.
https://github.com/jslirola/flarum-ext-login2seeplus

**Comment by northeaster** [comment]
https://github.com/FriendsOfFlarum/follow-tags uzantısında İngilizce yeni satırlar var.

**Comment by tolgaaaltas** [comment]
Teşekkürler şimdi hepsiyle ilgilenmeye başlıyorum.

**Comment by tolgaaaltas** [comment]
> ### bildirimlerde gördüğüm ingilizce satır:
> (Burası kullanıcı adı) changed the tag

Bunu hangi uzantı için yazdınız?

**Comment by tolgaaaltas** [comment]
> ### flarum-ext-audit-free uzantısı desteği ekler misiniz ?
> https://github.com/kilowhat/flarum-ext-audit-free
> 
> https://github.com/kilowhat/flarum-ext-audit-free/blob/master/resources/locale/en.yml

Bir kısmını çevirdim ancak bir süre sonra devam edebileceğim diğerlerine de göz atmam gerektiği için. Ana hatlarıyla çevrildi diye düşünüyorum.

**Comment by northeaster** [comment]
https://forum.sourceturk.net/ sitemden bakabilirsiniz. Güncellenen satırlar bende halen İngilizce.

**Comment by tolgaaaltas** [comment]
> https://forum.sourceturk.net/ sitemden bakabilirsiniz. Güncellenen satırlar bende halen İngilizce.

Önbellekleme ile ilgili bir uzantı kullanıyorsanız ondan kaynaklı olabilir.

**Comment by northeaster** [comment]
Onun ile ilgili olduğunu sanmıyorum. Dosyalarda bence bir sorun olabilir. İçeriğinde hata yada adlarında hata. Discord'dan iletişime geçebilirseniz. Bilgileri iletebilirim. **northeaster#8969**

**Comment by tolgaaaltas** [comment]
> Onun ile ilgili olduğunu sanmıyorum. Dosyalarda bence bir sorun olabilir. İçeriğinde hata yada adlarında hata. Discord'dan iletişime geçebilirseniz. Bilgileri iletebilirim. **northeaster#8969**

Discord kullanmıyorum, elektronik posta atabilirsiniz GitHub profilimde var. Bunun haricinde FlarumTR'de yeni satırlar düzgün gözüküyor.

**Comment by northeaster** [comment]
Dosya adları yanlış galiba. Dosya adlarını nasıl ayarlacagimi anlatır mısınız? Tüm yeni eklentiler ve ingilizce satırlar için gönderdiğim pr lar bu şekilde doğru olacaktır.

**Comment by tolgaaaltas** [comment]
> Dosya adları yanlış galiba. Dosya adlarını nasıl ayarlacagimi anlatır mısınız? Tüm yeni eklentiler ve ingilizce satırlar için gönderdiğim pr lar bu şekilde doğru olacaktır.

Merhaba,
Dosya adlarını uzantı ile ilgili çeviri metini içerisinde yer alan ilk satırdaki kısım dosya adı olmalıdır.
```
fof-drafts:
  admin:
    permissions:
      start: Tartışma için taslak oluştur
      schedule: Taslağı zamanla
    settings:
      title: Taslak Ayarları
      enable_scheduled_drafts: Zamanlanmış taslakları aç
  console:
    scheduled_drafts_disabled: Zamanlanmış taslıklar ayarlardan kapalıdır.
```

için dosya adı fof-drafts.yml olması gerekmektedir.

**Comment by northeaster** [comment]
kilowhat audit ve calendar eklentileri doğru ayarlanmış olmasına rağmen forumda gene İngilizce gözüküyor. O sorunu anlayamadım. Diğerleri için PR atacağım. Bu issue'yi kapatabilirsiniz.
